CREATE TABLE JUVE_MEMBER(
	JM_ID varchar2(16 char) PRIMARY KEY,
	JM_PASSWORD varchar2(64 char) NOT NULL,
	JM_NAME varchar2(4 char) NOT NULL,
	JM_ADDRESS varchar2(100 char) NOT NULL,
	JM_PHONE varchar2(13 char) NOT NULL,
	JM_TEL varchar2(14 char),
	JM_EMAIL varchar2(50 char) NOT NULL,
	JM_GENDER char (1 char) DEFAULT '0',
	JM_BIRTH DATE,
	JM_MILEAGE number(7) NOT null
);

SELECT * FROM JUVE_MEMBER ;

CREATE TABLE JUVE_PRODUCT(
	JP_PRODUCTCODE varchar2(7 char) PRIMARY KEY,
	JP_CATEGORY varchar2(3 char) NOT NULL,
	JP_PRODUCTNUM number(3) NOT NULL,
	JP_PRODUCTNAME varchar2(50 char) NOT NULL,
	JP_PRODUCTPRICE number(6) NOT NULL,
	JP_PRODUCTPHOTO varchar2(200 char)
);

DROP TABLE JUVE_PRODUCT;

DELETE FROM JUVE_PRODUCT;

SELECT * FROM juve_product;
